# -*- coding: utf-8 -*-
"""calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vc-xqnHc9VdmIkiE4d8i5cU0nDsie8ba

CALCULATOR CLI
"""

print("""Select arithmetic operation:
            1. Addition
            2. Division
            3. Modulus
            4. Multiplication
            5. Subtraction
""")

def print_answer(one, two, operation, answer):
    print(one, operation, two, "=", answer)

while True:
    try:
        selection = int(input("Select arithmetic operation (1-5): "))
    except ValueError:
        print("Invalid input. Please enter a number between 1 and 5.")
        continue

    if selection in (1, 2, 3, 4, 5):
        try:
            first_number = int(input("Enter first number: "))
            second_number = int(input("Enter second number: "))
        except ValueError:
            print("Invalid number input. Please enter integers.")
            continue

        if selection == 1:
            answer = first_number + second_number
            print_answer(first_number, second_number, "+", answer)

        elif selection == 2:
            if second_number == 0:
                print("Error: Division by zero.")
                continue
            answer = first_number / second_number
            print_answer(first_number, second_number, "/", answer)

        elif selection == 3:
            answer = first_number % second_number
            print_answer(first_number, second_number, "%", answer)

        elif selection == 4:
            answer = first_number * second_number
            print_answer(first_number, second_number, "*", answer)

        elif selection == 5:
            answer = first_number - second_number
            print_answer(first_number, second_number, "-", answer)

        next_calculation = input("Do you want to continue? (yes/no): ")
        if next_calculation.lower() != 'yes':
            print("Exiting the calculator.")
            break
    else:
        print("Invalid selection. Please enter a number between 1 and 5.")

